# Generated by Django 5.2.4 on 2025-08-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_status_alter_answer_attempt_alter_attempt_quiz_and_more'),
        ('core', '0003_quiz_status_alter_quiz_title'),
    ]

    operations = [
    ]
